services:
  frontend_svc:
    container_name: frontend
    build:
      context: ./frontend  
      dockerfile: Dockerfile  
    ports:
      - "4200:80"  
    restart: always
    depends_on:
      - backend_svc 
  backend_svc:
    container_name: backend
    build:
      context: ./backend  
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"  
    restart: always
