trigger:
  - task

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals vm-pkw-db-monitor

variables:
  - name: DOCKER_USERNAME
    value: $(DOCKER_USERNAME)
  - name: DOCKER_PASSWORD
    value: $(DOCKER_PASSWORD)
  - name: FRONTEND_IMAGE
    value: $(FRONTEND_IMAGE)
  - name: BACKEND_IMAGE
    value: $(BACKEND_IMAGE)
  - name: DOCKER_IMAGE_TAG
    value: $(DOCKER_IMAGE_TAG)

steps:
  - template: ./pipeline/steps-template.yml
    parameters:
      docker_username: $(DOCKER_USERNAME)
      docker_password: $(DOCKER_PASSWORD)
      frontend_image: $(FRONTEND_IMAGE)
      backend_image: $(BACKEND_IMAGE)
      docker_image_tag: $(DOCKER_IMAGE_TAG)
